# Generated by Django 5.1.4 on 2025-01-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='last_time_to_delivery',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_Id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_First_Name',
        ),
    ]
