# Generated by Django 3.2.25 on 2024-10-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalg', '0002_auto_20241023_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
